### ISSUE TITLE
Trying to get to vit versa I'm new

### ISSUE THREAD

**Issue by laurawingx** [julianschmuckli/fitbitos_swiss_railway_clock#1]
I love you clockface, played Borderlands. I'm super new to the fitbit dev and I figuring out how fix if for versa.

**Comment by julianschmuckli** [comment]
Hi, it should be fixed for Fitbit Versa and already published: https://gam.fitbit.com/gallery/clock/c991aef0-8216-4e47-8f75-ee09cee61665

**Comment by laurawingx** [comment]
Thanks, I'm learning a lot from your build. Appreciate it.
